#
# CONFIG OPTIONS
#
# min-night-speed-mult: The lowest possible night speed multiplier (if the tiniest fraction of players are sleeping)
# -- This value must be a whole number greater than 0
# -- Keep in mind that this is NOT the speed of night if a single player is sleeping. If 1 of 2 people are sleeping,
#    then the speed multiple will be halfway between the min and max multiples. SmoothSleep will scale the multiple
#    based on the ratio of people sleeping
# -- Vanilla time scale is used if there are no sleepers, not the min mult speed.
#
# max-night-speed-mult: The highest possible night speed multiplier (if everyone is sleeping)
# -- This value must be a whole number greater than 0
# -- For reference, a speed mult of 50 will make a full night take roughly 10 seconds
#
# morning-subtitle: The message shown under the clock upon waking up if 'use-titles' is enabled.
# -- Any short message with ampersand {&} color codes. Good idea to wrap this value in 'quotes' or it may break
# -- If you want to keep the clock, but not the subtitle, then just leave this blank (empty quotes '')
# -- Supports variables:
# -- -- {12H} - The 12-hour portion of the server time
# -- -- {24H} - The 24-hour portion of the server time
# -- -- {MIN} - The minutes portion of the server time
# -- -- {MER_UPPER} - The uppercase meridiem counterpart of 12-hour time, AM or PM
# -- -- {MER_LOWER} - The lowercase meridiem counterpart of 12-hour time, am or pm
# -- -- {SLEEPERS} - The number of players currently sleeping
# -- -- {WAKERS} - The number of non-ignored non-sleeping players
# -- -- {TOTAL} - The number of players sleeping + non-sleeping, non-ignored players
# -- -- {TIMESCALE} - How many times faster than normal time is passing
# -- -- {USERNAME} - The player's username (not always the one that is displayed in game)
# -- -- {DISPLAYNAME} - The player's name as it is shown in game. May contain prefixes, color codes, etc.
# -- -- {HOURS_SLEPT} - How many in-game hours the player has slept, regardless of timescale
# -- -- {LEVEL} - The player's current level
# -- -- {DAYS_LIVED} - The number of days that the player has lived
# -- -- {REM_HOURS_LIVED} - The number of hours the player has lived after subtracting days
# -- -- {REM_MINS_LIVED} - The number of minutes the player has lived after subtracting days and hours
# -- -- {TOTAL_HOURS_LIVED} - The number of hours that the player has lived (total hours, doesn't subtract days)
# -- -- {TOTAL_MINS_LIVED} - The number of minutes that the player has lived (total minutes, doesn't subtract hours or days)
# -- -- {TIME_LIVED} - The time the player has lived in days, minutes, and seconds; formatted as '0d, 0h, 0m'
# -- -- {WORLD} - The name of the world that the player is sleeping in
# -- -- {SERVER_IP} - 'server-ip' specified in server.properties
# -- -- {SERVER_MOTD} - 'motd' specified in server.properties (including colors)
# -- -- {SERVER_NAME} - 'server-name' specified in server.properties (including colors)
# -- -- {SERVER_MOTD_STRIP} - 'motd' specified in server.properties (stripped of colors)
# -- -- {SERVER_NAME_STRIP} - 'server-name' specified in server.properties (stripped of colors)
# -- -- {NICKNAME} - Essentials nickname without the group prefix. Same as DISPLAYNAME if essentials isn't installed.
# -- -- {NICKNAME_STRIP} - NICKNAME without colors or formats.
#
# morning-sound: If this is a valid sound, then it will play for a player when they wake up.
# -- For a list of valid sounds, refer to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# -- To disable this, just leave blank (empty quotes '')
#
# morning-particle-options:
# -- particle: The name of the particle to use. For a list, refer to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# -- -- Some particles require data. They will not work: REDSTONE, BLOCK_CRACK, BLOCK_DUST, FALLING_DUST, ITEM_CRACK
#       LEGACY_BLOCK_CRACK, LEGACY_BLOCK_DUST, LEGACY_FALLING_DUST, SPELL_MOB, SPELL_MOB_AMBIENT
# -- amount: The number of particle to spawn. This also controls how long the particles last since each ticks spawns a particle.
# -- radius: How far around the player the particles should spawn
#
# use-titles: If true, displays a large clock and sleeper stats when sleeping, and 'morning-subtitle' in the morning
#
# instant-day-if-all-sleeping: If true, this will instantly skip night if all non-sleep-ignored players are sleeping.
#
# essentials-settings:
# -- ignore-afk: If essentials is installed, setting this to true will exempt AFK player from needing to sleep
# -- ignore-vanished: Same as ignore-afk, but exempts vanished players from needing to sleep
#
# replenish-settings:
# -- heal-negative-statuses: If true, heals negative status effects if the player has slept the required hours
# -- hours-to-heal-negative: The hours of sleep required to heal negative statuses
# -- heal-positive-statuses: If true, heals positive status effects if the player has slept the required hours
# -- hours-to-heal-positive: The hours of sleep required to heal positive statuses
# -- ticks-per-health: Ticks to sleep (including timescaled ticks) to heal the amount specified
# -- health-amount: The amount healed per interval specified. Can be negative. 1 = half a heart
# -- ticks-per-food: Ticks to sleep (including timescaled ticks) to feed the amount specified
# -- food-amount: Ticks to sleep (including timescaled ticks) to feed the amount specified
#
# =============================
enable-stats: true
logging-settings:
  log-debug: false
  log-warning: true
  log-info: true
worlds:
  world:
    min-night-speed-mult: 10
    max-night-speed-mult: 50
    use-titles: true
    sleeping-title: '&b{12H}:{MIN} {MER_UPPER}'
    morning-title: '&e{12H}:{MIN} {MER_UPPER}'
    sleeping-subtitle: '&a{SLEEPERS}/{TOTAL} Sleeping &3({TIMESCALE}x speed)'
    morning-subtitle: '&aRise and shine, {USERNAME}!'
    morning-sound: 'ENTITY_PLAYER_LEVELUP'
    morning-particle-options:
      particle: 'VILLAGER_HAPPY'
      amount: 50
      radius: 1.5
    title-stay-ticks: 20
    title-fade-ticks: 40
    clear-weather-when-morning: true
    instant-day-if-all-sleeping: false
    essentials-settings:
      ignore-afk: true
      ignore-vanished: true
    replenish-settings:
      heal-negative-statuses: true
      hours-to-heal-negative: 3
      heal-positive-statuses: false
      hours-to-heal-positive: 3
      ticks-per-health: 3000
      health-amount: 1
      ticks-per-food: 3000
      food-amount: 0