# =============================
#
# SmoothSleep is intended to make sleeping a more fluid compromise between vanilla sleep mechanics and the
# jarring instant-daylight effect of majority-rules sleeping plugins. Rather than any number of players being
# required to set the time to day, SmoothSleep will scale the speed of night according to the number of
# players currently sleeping. It will keep players in bed while showing an on screen clock, how
# many players are sleeping, and the current speed at which night is passing.
#
# Additionally, sleep-ignored players are checked, so if another plugin sets a player as sleep
# ignored, SmoothSleep won't count them if they're awake. They WILL be counted if they're sleeping
# though (allowing them to participate and also fast-forward night if they're the only ones online)
#
# =============================
#
# CONFIG OPTIONS
#
# min-night-speed-mult: The lowest possible night speed multiplier (if the tiniest fraction of players are sleeping)
# -- This value must be a whole number greater than 0
# -- Keep in mind that this is NOT the speed of night if a single player is sleeping. If 1 of 2 people are sleeping,
#    then the speed multiple will be halfway between the min and max multiples. SmoothSleep will scale the multiple
#    based on the ratio of people sleeping
# -- Vanilla time scale is used if there are no sleepers, not the min mult speed.
#
# max-night-speed-mult: The highest possible night speed multiplier (if everyone is sleeping)
# -- This value must be a whole number greater than 0
# -- For reference, a speed mult of 50 will make a full night take roughly 10 seconds
#
# morning-subtitle: The message shown under the clock upon waking up if 'use-titles' is enabled.
# -- Any short message with ampersand {&} color codes. Good idea to wrap this value in 'quotes' or it may break
# -- If you want to keep the clock, but not the subtitle, then just leave this blank (empty quotes '')
# -- Supports variables:
# -- -- {12H} - The 12-hour portion of the server time
# -- -- {24H} - The 24-hour portion of the server time
# -- -- {MIN} - The minutes portion of the server time
# -- -- {MER_UPPER} - The uppercase meridiem counterpart of 12-hour time, AM or PM
# -- -- {MER_LOWER} - The lowercase meridiem counterpart of 12-hour time, am or pm
# -- -- {SLEEPERS} - The number of players currently sleeping
# -- -- {WAKERS} - The number of non-ignored non-sleeping players
# -- -- {TOTAL} - The number of players sleeping + non-sleeping, non-ignored players
# -- -- {TIMESCALE} - How many times faster than normal time is passing
# -- -- {USERNAME} - The player's username (not always the one that is displayed in game)
# -- -- {DISPLAYNAME} - The player's name as it is shown in game. May contain prefixes, color codes, etc.
# -- -- {HOURS_SLEPT} - How many in-game hours the player has slept, regardless of timescale
# -- -- {LEVEL} - The player's current level
# -- -- {DAYS_LIVED} - The number of days that the player has lived
# -- -- {REM_HOURS_LIVED} - The number of hours the player has lived after subtracting days
# -- -- {REM_MINS_LIVED} - The number of minutes the player has lived after subtracting days and hours
# -- -- {TOTAL_HOURS_LIVED} - The number of hours that the player has lived (total hours, doesn't subtract days)
# -- -- {TOTAL_MINS_LIVED} - The number of minutes that the player has lived (total minutes, doesn't subtract hours or days)
# -- -- {TIME_LIVED} - The time the player has lived in days, minutes, and seconds; formatted as '0d, 0h, 0m'
# -- -- {WORLD} - The name of the world that the player is sleeping in
# -- -- {SERVER_IP} - 'server-ip' specified in server.properties
# -- -- {SERVER_MOTD} - 'motd' specified in server.properties (including colors)
# -- -- {SERVER_NAME} - 'server-name' specified in server.properties (including colors)
# -- -- {SERVER_MOTD_STRIP} - 'motd' specified in server.properties (stripped of colors)
# -- -- {SERVER_NAME_STRIP} - 'server-name' specified in server.properties (stripped of colors)
#
# morning-sound: If this is a valid sound, then it will play for a player when they wake up.
# -- For a list of valid sounds, refer to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# -- To disable this, just leave blank (empty quotes '')
#
# use-titles: If true, displays a large clock and sleeper stats when sleeping, and 'morning-subtitle' in the morning
#
# instant-day-if-all-sleeping: If true, this will instantly skip night if all non-sleep-ignored players are sleeping.
#
# =============================
worlds:
  world:
    min-night-speed-mult: 10
    max-night-speed-mult: 50
    sleeping-title: '&b{12H}:{MIN} {MER_UPPER}'
    morning-title: '&e{12H}:{MIN} {MER_UPPER}'
    sleeping-subtitle: '&a{SLEEPERS}/{TOTAL} Sleeping &3({TIMESCALE}x speed)'
    morning-subtitle: '&aRise and shine, {USERNAME}!'
    morning-sound: 'ENTITY_PLAYER_LEVELUP'
    clear-weather-when-morning: true
    use-titles: true
    instant-day-if-all-sleeping: false