name: ${project.artifactId}
author: OffLuffy
description: ${project.description}
version: ${project.version}
main: ${project.groupId}.${project.name}.${project.name}
softdepend: [Essentials]
commands:
  smoothsleepreload:
    description: Reloads SmoothSleep's config values
    permission: "smoothsleep.reload"
    usage: /ssreload
    aliases: [ssreload, ssleepreload, sleepreload]
  smoothsleeptoggle:
    description: Disables or enables the plugin. It will enable itself after a relaod/restart.
    permission: "smoothsleep.toggle"
    usage: /sstoggle
    aliases: [sstoggle, ssleeptoggle, sleeptoggle]
permission:
  smoothsleep.reload:
    description: Allows reloading SmoothSleep config
    default: op
  smoothsleep.toggle:
    description: Allows toggling SmoothSleep on/off
    default: op