name: ${artifactId}
author: OffLuffy
description: ${project.description}
version: ${version}
main: ${project.groupId}.${project.name}.${project.name}
commands:
  smoothsleepreload:
    description: Reloads SmoothSleep's config values
    permission: "smoothsleep.reload"
    usage: /ssreload
    aliases: [ssreload, ssleepreload, sleepreload]
permission:
  smoothsleep.reload:
    description: Allows reloading SmoothSleep config
    default: op