name: CarbonSleep
author: OffLuffy
description: Sleep speed plugin for Team-Carbon
version: 1.0.0
depend: [Vault]
main: net.teamcarbon.carbonsleep.CarbonSleep
commands:
  carbonsleepreload:
    description: Reloads config values
    usage: /csreload
    aliases: [csreload, csleepreload, sleepreload]
permission:
  carbonsleep.reload:
    description: Allows reloading CarbonSleep config
    default: op