name: CarbonSleep
author: OffLuffy
description: Sleep speed plugin for Team-Carbon
version: 0.0.1
depend: [Vault]
main: net.teamcarbon.carbonsleep.CarbonSleep
commands:
  carbonsleepreload:
    description: Reloads config values
    usage: /csreload
    aliases: [csleepreload, sleepreload]
permission:
  carbonsleep.something:
    description: Allows something
    default: op